// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"time"

	null "gopkg.in/guregu/null.v4"
)

type Commit struct {
	ID           int32     `json:"id"`
	RepoFullName string    `json:"repo_full_name"`
	Sha          string    `json:"sha"`
	Message      string    `json:"message"`
	Url          string    `json:"url"`
	Author       string    `json:"author"`
	Date         time.Time `json:"date"`
}

type Repository struct {
	ID              int32     `json:"id"`
	Description     string    `json:"description"`
	Url             string    `json:"url"`
	Language        string    `json:"language"`
	RepoName        string    `json:"repo_name"`
	RepoFullName    string    `json:"repo_full_name"`
	ForksCount      null.Int  `json:"forks_count"`
	StarsCount      null.Int  `json:"stars_count"`
	OpenIssuesCount null.Int  `json:"open_issues_count"`
	WatchersCount   null.Int  `json:"watchers_count"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
