// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"context"
)

type Querier interface {
	CreateCommit(ctx context.Context, arg CreateCommitParams) error
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) error
	GetLastCommitSha(ctx context.Context) (string, error)
}

var _ Querier = (*Queries)(nil)
